version: '3.7'
services:
  app:
    container_name: app
    build: ./app
    command: |
      bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8000'
    volumes:
      - ./app/:/app/
    ports:
      - 8000:8000
    stdin_open: true
    tty: true
    environment:
      - DATABASE_URI=postgresql://testuser:password@db/backend_db
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    container_name: db
    environment:
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=backend_db
